### ISSUE TITLE
Want to Try Your Stuff

### ISSUE THREAD

**Issue by git-rearden** [TeamPhoenix-Ethdenver/FeelGood#1]
Hi,
I was at the denver hackathon, a colleague gave me a link to your project. I am trying to use it, got this far : 

Failed to compile.

./src/uport.js
Module not found: Can't resolve './key.json' in <>'/FeelGood/src' 

I imagine I need to do something with uPort? Pretty new to blockchain.  Can you give me a boost? 

Thanks

**Comment by eric6356** [comment]
You need to have a uPort app and get a key to make it run.
https://developer.uport.me/overview.html

I've updated the readme.

**Comment by git-rearden** [comment]
Hi Eric,
Thanks for the help. I have gotten this far maybe you'd be willing to give
me another hint.

If look at the http://localhost:3000/ get asked for Provider ? Blank page.

Got uPort mobile and app registered created the key.json as per your
instructions.

Went into truffle development from the /src dir, run migrate, get deployed
address for FeelGood, edit init_contract.js to use the deployed address in
the  first three const entities.

Output :
 truffle development
Connected to existing Truffle Develop session at http://localhost:9545/

truffle(develop)> migrate
Compiling
./../node_modules/zeppelin-solidity/contracts/ownership/rbac/RBAC.sol...
Compiling
./../node_modules/zeppelin-solidity/contracts/ownership/rbac/Roles.sol...
Compiling ./contracts/FeelGood.sol...
Compiling ./contracts/Migrations.sol...
Writing artifacts to ./build/contracts

Using network 'develop'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... 0x1f20d52337e024ec11c9cd6009f2d19369aadb877b367b3f338ba4a17b9efa1b
  Migrations: 0x95933dd6a1dd84b9d90d9b23c77976ae86c79f2b
Saving successful migration to network...
  ... 0x12b3df5b07df7fc7ca5db62f34c4c605e52c5e4fb9f6705483bf97a3014f47c1
Saving artifacts...
Running migration: 2_add_feel_good.js
  Deploying FeelGood...
  ... 0x93e84c1634fad20bcd2b8888e141f8d0b1b3896f99e8145f89b726b38457a082
  FeelGood: 0xfa1748127c5793526c37c2c5bc1149cd32ab98c8
Saving successful migration to network...
  ... 0x3e13f31d9bca8f9b0cd5812c7411d133ab70d73b6142271fd51941556c568b41
Saving artifacts...
truffle(develop)> exec init_contract.js
Using network 'develop'.

adding roles
{ tx: '0xdb12f36d6862542e858f5b4ca50f58e5ffaedf9103e9eeeaccf4cca200bdfb6b',
  receipt:
   { transactionHash:
'0xdb12f36d6862542e858f5b4ca50f58e5ffaedf9103e9eeeaccf4cca200bdfb6b',
     transactionIndex: 0,
     blockHash:
'0xa39a93d0809a197f903c803e74984f5aec1bdf2d76848f3590f70f1f5fbf7403',
     blockNumber: 316,
     gasUsed: 48387,
     cumulativeGasUsed: 48387,
     contractAddress: null,
     logs: [ [Object] ] },
  logs:
   [ { logIndex: 0,
       transactionIndex: 0,
       transactionHash:
'0xdb12f36d6862542e858f5b4ca50f58e5ffaedf9103e9eeeaccf4cca200bdfb6b',
       blockHash:
'0xa39a93d0809a197f903c803e74984f5aec1bdf2d76848f3590f70f1f5fbf7403',
       blockNumber: 316,
       address: '0xfa1748127c5793526c37c2c5bc1149cd32ab98c8',
       type: 'mined',
       event: 'RoleAdded',
       args: [Object] } ] }
{ tx: '0xdaff10d755f84e392abea008096a81623915860fd0cb912258d2cf8d7ef4ce20',
  receipt:
   { transactionHash:
'0xdaff10d755f84e392abea008096a81623915860fd0cb912258d2cf8d7ef4ce20',
     transactionIndex: 0,
     blockHash:
'0x322b6eca3e37181677230c0da8c6a68209aff5f720a3484848d9a8333736b1c7',
     blockNumber: 317,
     gasUsed: 48131,
     cumulativeGasUsed: 48131,
     contractAddress: null,
     logs: [ [Object] ] },
  logs:
   [ { logIndex: 0,
       transactionIndex: 0,
       transactionHash:
'0xdaff10d755f84e392abea008096a81623915860fd0cb912258d2cf8d7ef4ce20',
       blockHash:
'0x322b6eca3e37181677230c0da8c6a68209aff5f720a3484848d9a8333736b1c7',
       blockNumber: 317,
       address: '0xfa1748127c5793526c37c2c5bc1149cd32ab98c8',
       type: 'mined',
       event: 'RoleAdded',
       args: [Object] } ] }
{ tx: '0x0d1ce491453a329534f9d32b7881e9f615e0d3999884d510eef51cedb44bf938',
  receipt:
   { transactionHash:
'0x0d1ce491453a329534f9d32b7881e9f615e0d3999884d510eef51cedb44bf938',
     transactionIndex: 0,
     blockHash:
'0x3f40a8c12c77e036119c98345a87231da1f8fd7320c4e8bf4d0a26df3e8880e2',
     blockNumber: 318,
     gasUsed: 48259,
     cumulativeGasUsed: 48259,
     contractAddress: null,
     logs: [ [Object] ] },
  logs:
   [ { logIndex: 0,
       transactionIndex: 0,
       transactionHash:
'0x0d1ce491453a329534f9d32b7881e9f615e0d3999884d510eef51cedb44bf938',
       blockHash:
'0x3f40a8c12c77e036119c98345a87231da1f8fd7320c4e8bf4d0a26df3e8880e2',
       blockNumber: 318,
       address: '0xfa1748127c5793526c37c2c5bc1149cd32ab98c8',
       type: 'mined',
       event: 'RoleAdded',
       args: [Object] } ] }
{ tx: '0x591cecb4a8ac17901940c4c3b8138a09a0bd65428c0842c8e58d88be185d834a',
  receipt:
   { transactionHash:
'0x591cecb4a8ac17901940c4c3b8138a09a0bd65428c0842c8e58d88be185d834a',
     transactionIndex: 0,
     blockHash:
'0x485481b7659adefba14cc19a3cfed75ab699106447c4433e454d472554cc0491',
     blockNumber: 319,
     gasUsed: 48387,
     cumulativeGasUsed: 48387,
     contractAddress: null,
     logs: [ [Object] ] },
  logs:
   [ { logIndex: 0,
       transactionIndex: 0,
       transactionHash:
'0x591cecb4a8ac17901940c4c3b8138a09a0bd65428c0842c8e58d88be185d834a',
       blockHash:
'0x485481b7659adefba14cc19a3cfed75ab699106447c4433e454d472554cc0491',
       blockNumber: 319,
       address: '0xfa1748127c5793526c37c2c5bc1149cd32ab98c8',
       type: 'mined',
       event: 'RoleAdded',
       args: [Object] } ] }
{ tx: '0xc2cbee1ba8670a521ac64795ea678aa6e1666a9b57bb9a4a8be6eadc7d034307',
  receipt:
   { transactionHash:
'0xc2cbee1ba8670a521ac64795ea678aa6e1666a9b57bb9a4a8be6eadc7d034307',
     transactionIndex: 0,
     blockHash:
'0xba4ad3394e126e4cf2abe3cfbf5ab1ca3e50e4e36bc51cf9ccd4bfe8153f86ad',
     blockNumber: 320,
     gasUsed: 48131,
     cumulativeGasUsed: 48131,
     contractAddress: null,
     logs: [ [Object] ] },
  logs:
   [ { logIndex: 0,
       transactionIndex: 0,
       transactionHash:
'0xc2cbee1ba8670a521ac64795ea678aa6e1666a9b57bb9a4a8be6eadc7d034307',
       blockHash:
'0xba4ad3394e126e4cf2abe3cfbf5ab1ca3e50e4e36bc51cf9ccd4bfe8153f86ad',
       blockNumber: 320,
       address: '0xfa1748127c5793526c37c2c5bc1149cd32ab98c8',
       type: 'mined',
       event: 'RoleAdded',
       args: [Object] } ] }
{ tx: '0x9298837d852b548147e1c7911d770fc23a427e5f554cc4f3d24b12c49a658b3f',
  receipt:
   { transactionHash:
'0x9298837d852b548147e1c7911d770fc23a427e5f554cc4f3d24b12c49a658b3f',
     transactionIndex: 0,
     blockHash:
'0x97439305c32c8ee970d7178ab3cc7f44bbcf11646f4aebb5009ae237e0dd3dd0',
     blockNumber: 321,
     gasUsed: 48259,
     cumulativeGasUsed: 48259,
     contractAddress: null,
     logs: [ [Object] ] },
  logs:
   [ { logIndex: 0,
       transactionIndex: 0,
       transactionHash:
'0x9298837d852b548147e1c7911d770fc23a427e5f554cc4f3d24b12c49a658b3f',
       blockHash:
'0x97439305c32c8ee970d7178ab3cc7f44bbcf11646f4aebb5009ae237e0dd3dd0',
       blockNumber: 321,
       address: '0xfa1748127c5793526c37c2c5bc1149cd32ab98c8',
       type: 'mined',
       event: 'RoleAdded',
       args: [Object] } ] }
adding Alice, Bob, Claire, David
(node:5067) UnhandledPromiseRejectionWarning: Unhandled promise rejection
(rejection id: 1): Error: VM Exception while processing transaction:
invalid opcode
truffle(develop)>

Am I getting closer ? Any advice?

I hope you don't mind my asking .....

Thanks very much.
Scott Martin

PS
I have a prototype of of a blockchained blood supply chain that I am using
to talk with blood banks in the Devner area. Maybe we could chat sometime
and calibrate - once I get to see your work running ?
